### ISSUE TITLE
doesn't seem to work with either public or private client key

### ISSUE THREAD

**Issue by tconroy** [rbnh/todoist-alfred-workflow#4]
Hey there,
seems this workflow has been outdated by changes to the Todoist API. I get the post notification, but the task never shows up in my todoist account. I've tried both the public and private API keys, no dice.

Any chance we could get an update? :)

**Comment by rubenschmidtmann** [comment]
Hej there, I'll try to move to the latest API version in the upcoming weeks. Thanks!

**Comment by AntonNiklasson** [comment]
It seems to be working for me. I used the token I found in _Todoist Settings_ > _Account_.

Did that not work for you?
